apiVersion: v1
kind: Service
metadata:
  name: campusgo-app
  namespace: campusgo
spec:
  selector:
    app: campusgo-app

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082

  type: NodePort