apiVersion: v1
kind: ConfigMap
metadata:
  name: campusgo-config
  namespace: campusgo
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://campusgo-db:5432/campusgo
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_USERNAME: campusgo
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_H2_CONSOLE_ENABLED: "false"
  SERVER_PORT: "8081"
  JWT_EXPIRATION_MINUTES: "60"
