apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusgo-app
  namespace: campusgo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: campusgo-app

  template:
    metadata:
      labels:
        app: campusgo-app

    spec:
      containers:
        - name: campusgo

          image: campusgo:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: campusgo-config

          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: campusgo-secret
                  key: POSTGRES_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: campusgo-secret
                  key: JWT_SECRET

          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3