apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusgo-db
  namespace: campusgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campusgo-db
  template:
    metadata:
      labels:
        app: campusgo-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: campusgo

            - name: POSTGRES_USER
              value: campusgo

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: campusgo-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U campusgo -d campusgo
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U campusgo -d campusgo
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: campusgo-postgres-pvc