apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campusgo-postgres-pvc
  namespace: campusgo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi